{% set name = "pinotdb" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pinotdb-{{ version }}.tar.gz
  sha256: 7a4642b0659eb06933ff61b4cdf41500d274e048052ef27cbbc7966001c4a188

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - ciso8601 >=2.1.3,<3.0.0
    - h11 0.16.0
    - httpx >=0.28.1,<0.29
    - requests >=2.25.0,<3.0.0
    - urllib3 ==2.6.0

test:
  imports:
    - pinotdb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python-pinot-dbapi/pinot-dbapi
  summary: Python DB-API and SQLAlchemy dialect for Pinot.
  license: MIT
  license_file: LICENSE
  doc_url: http://kylin.apache.org/docs/
  dev_url: https://github.com/python-pinot-dbapi/pinot-dbapi

extra:
  recipe-maintainers:
    - xylar
