{% set name = "pinotdb" %}
{% set version = "5.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pinotdb-{{ version }}.tar.gz
  sha256: 4381469588a4656ac549eb9391fafe8fc3e325b11ec0b894a1b48fe7d4dd0b2b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.7,<4.0
    - ciso8601 >=2.1.3,<3.0.0
    - httpx >=0.23.0,<0.24.0
    - requests >=2.25.0,<3.0.0

test:
  imports:
    - pinotdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-pinot-dbapi/pinot-dbapi
  summary: Python DB-API and SQLAlchemy dialect for Pinot.
  license: MIT
  license_file: LICENSE
  doc_url: http://kylin.apache.org/docs/
  dev_url: https://github.com/python-pinot-dbapi/pinot-dbapi

extra:
  recipe-maintainers:
    - xylar
